
name: publish new tag

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-latest-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ cat VERSION }}
          message: "Release for $(cat VERSION)"

