
name: publish new tag

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-latest-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    
      - uses: actions/checkout@v3

      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV


      - run: echo ${{ steps.checkTag.outputs.exists }}
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: 'v${{ env.VERSION }}'
          message: "Release for v${{ env.VERSION }}"

